import type { Question } from './types';

export const questions: Question[] = [
  {
    id: 'phy102-q1',
    text: 'What is the fundamental law of electrostatics?',
    options: [
      { id: 'phy102-q1-o1', text: 'Opposite charges attract, like charges repel' },
      { id: 'phy102-q1-o2', text: 'All charges attract each other' },
      { id: 'phy102-q1-o3', text: 'Like charges attract, opposite charges repel' },
      { id: 'phy102-q1-o4', text: 'Charges of the same magnitude cancel each other' },
    ],
    correctOptionId: 'phy102-q1-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q2',
    text: 'Which of the following is NOT a good conductor?',
    options: [
      { id: 'phy102-q2-o1', text: 'Copper' },
      { id: 'phy102-q2-o2', text: 'Aluminum' },
      { id: 'phy102-q2-o3', text: 'Rubber' },
      { id: 'phy102-q2-o4', text: 'Human body' },
    ],
    correctOptionId: 'phy102-q2-o3',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q3',
    text: 'When a glass rod is rubbed with silk, the glass rod becomes positively charged because:',
    options: [
      { id: 'phy102-q3-o1', text: 'It gains protons' },
      { id: 'phy102-q3-o2', text: 'It loses electrons' },
      { id: 'phy102-q3-o3', text: 'It gains electrons' },
      { id: 'phy102-q3-o4', text: 'It loses protons' },
    ],
    correctOptionId: 'phy102-q3-o2',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q4',
    text: 'Two point charges of +2 μC and -3 μC are separated by 0.1 m. What is the magnitude of the force between them? (k = 9 × 10⁹ Nm²/C²)',
    options: [
      { id: 'phy102-q4-o1', text: '5.4 N' },
      { id: 'phy102-q4-o2', text: '54 N' },
      { id: 'phy102-q4-o3', text: '0.54 N' },
      { id: 'phy102-q4-o4', text: '540 N' },
    ],
    correctOptionId: 'phy102-q4-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q5',
    text: 'Electric field lines around a positive point charge:',
    options: [
      { id: 'phy102-q5-o1', text: 'Point inward toward the charge' },
      { id: 'phy102-q5-o2', text: 'Form closed loops' },
      { id: 'phy102-q5-o3', text: 'Point outward from the charge' },
      { id: 'phy102-q5-o4', text: 'Are parallel straight lines' },
    ],
    correctOptionId: 'phy102-q5-o3',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q6',
    text: 'The SI unit of electric field intensity is:',
    options: [
      { id: 'phy102-q6-o1', text: 'Volt' },
      { id: 'phy102-q6-o2', text: 'Newton/Coulomb' },
      { id: 'phy102-q6-o3', text: 'Joule/Coulomb' },
      { id: 'phy102-q6-o4', text: 'Coulomb/Newton' },
    ],
    correctOptionId: 'phy102-q6-o2',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q7',
    text: 'What is the electric field at a point 0.5 m from a +4 μC charge?',
    options: [
      { id: 'phy102-q7-o1', text: '1.44 × 10⁵ N/C' },
      { id: 'phy102-q7-o2', text: '7.2 × 10⁴ N/C' },
      { id: 'phy102-q7-o3', text: '3.6 × 10⁴ N/C' },
      { id: 'phy102-q7-o4', text: '1.8 × 10⁵ N/C' },
    ],
    correctOptionId: 'phy102-q7-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q8',
    text: 'Electric flux through a surface is maximum when:',
    options: [
      { id: 'phy102-q8-o1', text: 'The surface is parallel to the field' },
      { id: 'phy102-q8-o2', text: 'The surface is perpendicular to the field' },
      { id: 'phy102-q8-o3', text: 'The surface is at 45° to the field' },
      { id: 'phy102-q8-o4', text: 'The surface is curved' },
    ],
    correctOptionId: 'phy102-q8-o2',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q9',
    text: "Gauss's law states that the net electric flux through any closed surface is equal to:",
    options: [
      { id: 'phy102-q9-o1', text: 'The charge enclosed divided by ε₀' },
      { id: 'phy102-q9-o2', text: 'The total charge outside the surface' },
      { id: 'phy102-q9-o3', text: 'The product of all charges' },
      { id: 'phy102-q9-o4', text: 'Zero always' },
    ],
    correctOptionId: 'phy102-q9-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q10',
    text: 'The work done in moving a unit positive charge from one point to another in an electric field is called:',
    options: [
      { id: 'phy102-q10-o1', text: 'Electric potential difference' },
      { id: 'phy102-q10-o2', text: 'Electric field intensity' },
      { id: 'phy102-q10-o3', text: 'Electric flux' },
      { id: 'phy102-q10-o4', text: 'Electric dipole moment' },
    ],
    correctOptionId: 'phy102-q10-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q11',
    text: 'The relationship between electric field E and potential V is:',
    options: [
      { id: 'phy102-q11-o1', text: 'E = -dV/dx' },
      { id: 'phy102-q11-o2', text: 'V = -dE/dx' },
      { id: 'phy102-q11-o3', text: 'E = V/d' },
      { id: 'phy102-q11-o4', text: 'V = E/d' },
    ],
    correctOptionId: 'phy102-q11-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q12',
    text: 'What is the potential at a point 0.2 m from a +5 nC charge?',
    options: [
      { id: 'phy102-q12-o1', text: '225 V' },
      { id: 'phy102-q12-o2', text: '450 V' },
      { id: 'phy102-q12-o3', text: '112.5 V' },
      { id: 'phy102-q12-o4', text: '900 V' },
    ],
    correctOptionId: 'phy102-q12-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q13',
    text: 'A capacitor is primarily used to:',
    options: [
      { id: 'phy102-q13-o1', text: 'Store electric charge' },
      { id: 'phy102-q13-o2', text: 'Regulate current' },
      { id: 'phy102-q13-o3', text: 'Increase resistance' },
      { id: 'phy102-q13-o4', text: 'Generate EMF' },
    ],
    correctOptionId: 'phy102-q13-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q14',
    text: 'The capacitance of a parallel-plate capacitor does NOT depend on:',
    options: [
      { id: 'phy102-q14-o1', text: 'The area of the plates' },
      { id: 'phy102-q14-o2', text: 'The distance between plates' },
      { id: 'phy102-q14-o3', text: 'The charge on the plates' },
      { id: 'phy102-q14-o4', text: 'The dielectric material between plates' },
    ],
    correctOptionId: 'phy102-q14-o3',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q15',
    text: 'For a parallel-plate capacitor with plate area A and separation d, the capacitance is given by:',
    options: [
      { id: 'phy102-q15-o1', text: 'C = ε₀A/d' },
      { id: 'phy102-q15-o2', text: 'C = ε₀d/A' },
      { id: 'phy102-q15-o3', text: 'C = A/(ε₀d)' },
      { id: 'phy102-q15-o4', text: 'C = d/(ε₀A)' },
    ],
    correctOptionId: 'phy102-q15-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q16',
    text: 'When a dielectric is inserted between the plates of a capacitor, the capacitance:',
    options: [
      { id: 'phy102-q16-o1', text: 'Increases' },
      { id: 'phy102-q16-o2', text: 'Decreases' },
      { id: 'phy102-q16-o3', text: 'Remains the same' },
      { id: 'phy102-q16-o4', text: 'Becomes zero' },
    ],
    correctOptionId: 'phy102-q16-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q17',
    text: 'Three 6 μF capacitors are connected in series. The equivalent capacitance is:',
    options: [
      { id: 'phy102-q17-o1', text: '18 μF' },
      { id: 'phy102-q17-o2', text: '2 μF' },
      { id: 'phy102-q17-o3', text: '9 μF' },
      { id: 'phy102-q17-o4', text: '3 μF' },
    ],
    correctOptionId: 'phy102-q17-o2',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q18',
    text: 'Three 4 μF capacitors are connected in parallel. The equivalent capacitance is:',
    options: [
      { id: 'phy102-q18-o1', text: '12 μF' },
      { id: 'phy102-q18-o2', text: '4 μF' },
      { id: 'phy102-q18-o3', text: '1.33 μF' },
      { id: 'phy102-q18-o4', text: '8 μF' },
    ],
    correctOptionId: 'phy102-q18-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q19',
    text: 'The energy stored in a capacitor is given by:',
    options: [
      { id: 'phy102-q19-o1', text: '½CV²' },
      { id: 'phy102-q19-o2', text: 'CV²' },
      { id: 'phy102-q19-o3', text: '½QV' },
      { id: 'phy102-q19-o4', text: 'Both A and C' },
    ],
    correctOptionId: 'phy102-q19-o4',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q20',
    text: 'A 10 μF capacitor is charged to 100 V. The energy stored is:',
    options: [
      { id: 'phy102-q20-o1', text: '0.05 J' },
      { id: 'phy102-q20-o2', text: '0.1 J' },
      { id: 'phy102-q20-o3', text: '0.01 J' },
      { id: 'phy102-q20-o4', text: '0.5 J' },
    ],
    correctOptionId: 'phy102-q20-o1',
    topic: 'Chapter 1: Electrostatics & Capacitors',
  },
  {
    id: 'phy102-q71',
    text: 'The SI unit of electric current is:',
    options: [
        { id: 'phy102-q71-o1', text: 'Coulomb' },
        { id: 'phy102-q71-o2', text: 'Volt' },
        { id: 'phy102-q71-o3', text: 'Ampere' },
        { id: 'phy102-q71-o4', text: 'Ohm' },
    ],
    correctOptionId: 'phy102-q71-o3',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q72',
    text: 'Current in a metal conductor is due to the flow of:',
    options: [
        { id: 'phy102-q72-o1', text: 'Protons' },
        { id: 'phy102-q72-o2', text: 'Neutrons' },
        { id: 'phy102-q72-o3', text: 'Electrons' },
        { id: 'phy102-q72-o4', text: 'Positive ions' },
    ],
    correctOptionId: 'phy102-q72-o3',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q73',
    text: 'If 2 × 10¹⁹ electrons pass through a wire in 4 seconds, the current is:',
    options: [
        { id: 'phy102-q73-o1', text: '0.4 A' },
        { id: 'phy102-q73-o2', text: '0.8 A' },
        { id: 'phy102-q73-o3', text: '1.2 A' },
        { id: 'phy102-q73-o4', text: '1.6 A' },
    ],
    correctOptionId: 'phy102-q73-o2',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q74',
    text: 'The drift velocity of electrons in a conductor:',
    options: [
        { id: 'phy102-q74-o1', text: 'Is very large (comparable to speed of light)' },
        { id: 'phy102-q74-o2', text: 'Is very small (few mm/s)' },
        { id: 'phy102-q74-o3', text: 'Is zero in DC circuits' },
        { id: 'phy102-q74-o4', text: 'Depends only on temperature' },
    ],
    correctOptionId: 'phy102-q74-o2',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q75',
    text: "Ohm's law states that:",
    options: [
        { id: 'phy102-q75-o1', text: 'V = I/R' },
        { id: 'phy102-q75-o2', text: 'I = V/R' },
        { id: 'phy102-q75-o3', text: 'R = V/I' },
        { id: 'phy102-q75-o4', text: 'Both B and C' },
    ],
    correctOptionId: 'phy102-q75-o4',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q76',
    text: "Which of the following obeys Ohm's law?",
    options: [
        { id: 'phy102-q76-o1', text: 'Diode' },
        { id: 'phy102-q76-o2', text: 'Thermistor' },
        { id: 'phy102-q76-o3', text: 'Copper wire' },
        { id: 'phy102-q76-o4', text: 'Transistor' },
    ],
    correctOptionId: 'phy102-q76-o3',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q77',
    text: 'The resistance of a wire depends on:',
    options: [
        { id: 'phy102-q77-o1', text: 'Length only' },
        { id: 'phy102-q77-o2', text: 'Cross-sectional area only' },
        { id: 'phy102-q77-o3', text: 'Material only' },
        { id: 'phy102-q77-o4', text: 'All of the above' },
    ],
    correctOptionId: 'phy102-q77-o4',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q78',
    text: 'The resistivity of a material of length L, cross-sectional area A, and resistance R is given by:',
    options: [
        { id: 'phy102-q78-o1', text: 'ρ = RA/L' },
        { id: 'phy102-q78-o2', text: 'ρ = RL/A' },
        { id: 'phy102-q78-o3', text: 'ρ = LA/R' },
        { id: 'phy102-q78-o4', text: 'ρ = A/(RL)' },
    ],
    correctOptionId: 'phy102-q78-o1',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q79',
    text: 'When resistors are connected in series:',
    options: [
        { id: 'phy102-q79-o1', text: 'Current is the same through each' },
        { id: 'phy102-q79-o2', text: 'Voltage is the same across each' },
        { id: 'phy102-q79-o3', text: 'Equivalent resistance decreases' },
        { id: 'phy102-q79-o4', text: 'Power dissipation is minimum' },
    ],
    correctOptionId: 'phy102-q79-o1',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q80',
    text: 'When resistors are connected in parallel:',
    options: [
        { id: 'phy102-q80-o1', text: 'Current is the same through each' },
        { id: 'phy102-q80-o2', text: 'Voltage is the same across each' },
        { id: 'phy102-q80-o3', text: 'Equivalent resistance increases' },
        { id: 'phy102-q80-o4', text: 'Power dissipation is maximum' },
    ],
    correctOptionId: 'phy102-q80-o2',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q81',
    text: 'Three resistors of 2Ω, 3Ω, and 6Ω are connected in parallel. The equivalent resistance is:',
    options: [
        { id: 'phy102-q81-o1', text: '1Ω' },
        { id: 'phy102-q81-o2', text: '11Ω' },
        { id: 'phy102-q81-o3', text: '0.5Ω' },
        { id: 'phy102-q81-o4', text: '1.5Ω' },
    ],
    correctOptionId: 'phy102-q81-o1',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q82',
    text: 'The power dissipated in a resistor R carrying current I is:',
    options: [
        { id: 'phy102-q82-o1', text: 'I²R' },
        { id: 'phy102-q82-o2', text: 'V²/R' },
        { id: 'phy102-q82-o3', text: 'VI' },
        { id: 'phy102-q82-o4', text: 'All of the above' },
    ],
    correctOptionId: 'phy102-q82-o4',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q83',
    text: 'A 100W lamp operates at 220V. The current through it is:',
    options: [
        { id: 'phy102-q83-o1', text: '0.45 A' },
        { id: 'phy102-q83-o2', text: '2.2 A' },
        { id: 'phy102-q83-o3', text: '4.5 A' },
        { id: 'phy102-q83-o4', text: '22 A' },
    ],
    correctOptionId: 'phy102-q83-o1',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q84',
    text: 'EMF of a cell is defined as:',
    options: [
        { id: 'phy102-q84-o1', text: 'The potential difference across its terminals when no current flows' },
        { id: 'phy102-q84-o2', text: 'The work done per unit charge in driving charge around the circuit' },
        { id: 'phy102-q84-o3', text: 'Both A and B' },
        { id: 'phy102-q84-o4', text: 'The potential difference across its terminals when current flows' },
    ],
    correctOptionId: 'phy102-q84-o3',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q85',
    text: 'The terminal voltage of a cell is less than its EMF when:',
    options: [
        { id: 'phy102-q85-o1', text: 'No current flows' },
        { id: 'phy102-q85-o2', text: 'Current flows through it' },
        { id: 'phy102-q85-o3', text: 'The cell is new' },
        { id: 'phy102-q85-o4', text: 'The internal resistance is zero' },
    ],
    correctOptionId: 'phy102-q85-o2',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q86',
    text: "Kirchhoff's current law is based on conservation of:",
    options: [
        { id: 'phy102-q86-o1', text: 'Energy' },
        { id: 'phy102-q86-o2', text: 'Charge' },
        { id: 'phy102-q86-o3', text: 'Momentum' },
        { id: 'phy102-q86-o4', text: 'Mass' },
    ],
    correctOptionId: 'phy102-q86-o2',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q87',
    text: "Kirchhoff's voltage law is based on conservation of:",
    options: [
        { id: 'phy102-q87-o1', text: 'Energy' },
        { id: 'phy102-q87-o2', text: 'Charge' },
        { id: 'phy102-q87-o3', text: 'Momentum' },
        { id: 'phy102-q87-o4', text: 'Mass' },
    ],
    correctOptionId: 'phy102-q87-o1',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q88',
    text: 'In a Wheatstone bridge, the bridge is balanced when:',
    options: [
        { id: 'phy102-q88-o1', text: 'No current flows through the galvanometer' },
        { id: 'phy102-q88-o2', text: 'Current is maximum through the galvanometer' },
        { id: 'phy102-q88-o3', text: 'The ratio of resistors is R₁/R₂ = R₃/R₄' },
        { id: 'phy102-q88-o4', text: 'Both A and C' },
    ],
    correctOptionId: 'phy102-q88-o4',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q89',
    text: 'A potentiometer is preferred over a voltmeter for accurate EMF measurement because:',
    options: [
        { id: 'phy102-q89-o1', text: 'It draws current from the cell' },
        { id: 'phy102-q89-o2', text: "It doesn't draw current from the cell" },
        { id: 'phy102-q89-o3', text: 'It has high resistance' },
        { id: 'phy102-q89-o4', text: 'It measures potential difference directly' },
    ],
    correctOptionId: 'phy102-q89-o2',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q90',
    text: 'Thermoelectricity refers to:',
    options: [
        { id: 'phy102-q90-o1', text: 'Conversion of heat to electricity' },
        { id: 'phy102-q90-o2', text: 'Conversion of electricity to heat' },
        { id: 'phy102-q90-o3', text: 'Both A and B' },
        { id: 'phy102-q90-o4', text: 'Heating effect of current only' },
    ],
    correctOptionId: 'phy102-q90-o3',
    topic: 'Chapter 2: Current Electricity',
  },
  {
    id: 'phy102-q141',
    text: 'The SI unit of magnetic field B is:',
    options: [
        { id: 'phy102-q141-o1', text: 'Gauss' },
        { id: 'phy102-q141-o2', text: 'Weber' },
        { id: 'phy102-q141-o3', text: 'Tesla' },
        { id: 'phy102-q141-o4', text: 'Henry' },
    ],
    correctOptionId: 'phy102-q141-o3',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q142',
    text: '1 Tesla is equal to:',
    options: [
        { id: 'phy102-q142-o1', text: '10⁴ Gauss' },
        { id: 'phy102-q142-o2', text: '10⁻⁴ Gauss' },
        { id: 'phy102-q142-o3', text: '10² Gauss' },
        { id: 'phy102-q142-o4', text: '10 Gauss' },
    ],
    correctOptionId: 'phy102-q142-o1',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q143',
    text: 'Magnetic field lines:',
    options: [
        { id: 'phy102-q143-o1', text: 'Start from north pole and end at south pole' },
        { id: 'phy102-q143-o2', text: 'Start from south pole and end at north pole' },
        { id: 'phy102-q143-o3', text: 'Form closed loops' },
        { id: 'phy102-q143-o4', text: 'Cross each other' },
    ],
    correctOptionId: 'phy102-q143-o3',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q144',
    text: 'The magnetic force on a charged particle moving in a magnetic field is maximum when the angle between velocity and field is:',
    options: [
        { id: 'phy102-q144-o1', text: '0°' },
        { id: 'phy102-q144-o2', text: '45°' },
        { id: 'phy102-q144-o3', text: '90°' },
        { id: 'phy102-q144-o4', text: '180°' },
    ],
    correctOptionId: 'phy102-q144-o3',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q145',
    text: 'The magnetic force on a charged particle is zero when it moves:',
    options: [
        { id: 'phy102-q145-o1', text: 'Perpendicular to the field' },
        { id: 'phy102-q145-o2', text: 'At 45° to the field' },
        { id: 'phy102-q145-o3', text: 'Parallel to the field' },
        { id: 'phy102-q145-o4', text: 'Opposite to the field direction' },
    ],
    correctOptionId: 'phy102-q145-o3',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q146',
    text: 'According to the right-hand rule for magnetic force, the thumb points in the direction of:',
    options: [
        { id: 'phy102-q146-o1', text: 'Magnetic field' },
        { id: 'phy102-q146-o2', text: 'Velocity of positive charge' },
        { id: 'phy102-q146-o3', text: 'Force on positive charge' },
        { id: 'phy102-q146-o4', text: 'Current' },
    ],
    correctOptionId: 'phy102-q146-o3',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q147',
    text: 'A proton enters a magnetic field perpendicularly. The path of the proton will be:',
    options: [
        { id: 'phy102-q147-o1', text: 'Straight line' },
        { id: 'phy102-q147-o2', text: 'Parabolic' },
        { id: 'phy102-q147-o3', text: 'Circular' },
        { id: 'phy102-q147-o4', text: 'Elliptical' },
    ],
    correctOptionId: 'phy102-q147-o3',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q148',
    text: 'The radius of the circular path of a charged particle in a magnetic field depends on:',
    options: [
        { id: 'phy102-q148-o1', text: 'Mass only' },
        { id: 'phy102-q148-o2', text: 'Speed only' },
        { id: 'phy102-q148-o3', text: 'Charge only' },
        { id: 'phy102-q148-o4', text: 'All of the above' },
    ],
    correctOptionId: 'phy102-q148-o4',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q149',
    text: 'Magnetic flux through a surface is defined as:',
    options: [
        { id: 'phy102-q149-o1', text: 'B × A' },
        { id: 'phy102-q149-o2', text: 'B·A' },
        { id: 'phy102-q149-o3', text: 'B/A' },
        { id: 'phy102-q149-o4', text: 'A/B' },
    ],
    correctOptionId: 'phy102-q149-o2',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q150',
    text: "According to Gauss's law for magnetism, the magnetic flux through a closed surface is:",
    options: [
        { id: 'phy102-q150-o1', text: 'Proportional to charge enclosed' },
        { id: 'phy102-q150-o2', text: 'Always positive' },
        { id: 'phy102-q150-o3', text: 'Always zero' },
        { id: 'phy102-q150-o4', text: 'Always negative' },
    ],
    correctOptionId: 'phy102-q150-o3',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q151',
    text: 'Which material is strongly attracted to a magnet?',
    options: [
        { id: 'phy102-q151-o1', text: 'Paramagnetic' },
        { id: 'phy102-q151-o2', text: 'Diamagnetic' },
        { id: 'phy102-q151-o3', text: 'Ferromagnetic' },
        { id: 'phy102-q151-o4', text: 'Non-magnetic' },
    ],
    correctOptionId: 'phy102-q151-o3',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q152',
    text: 'The Biot-Savart law gives:',
    options: [
        { id: 'phy102-q152-o1', text: 'Electric field due to current element' },
        { id: 'phy102-q152-o2', text: 'Magnetic field due to current element' },
        { id: 'phy102-q152-o3', text: 'Electric force on a charge' },
        { id: 'phy102-q152-o4', text: 'Magnetic force on a charge' },
    ],
    correctOptionId: 'phy102-q152-o2',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q153',
    text: 'The magnetic field due to a long straight current-carrying conductor at a distance r is:',
    options: [
        { id: 'phy102-q153-o1', text: 'Proportional to r' },
        { id: 'phy102-q153-o2', text: 'Proportional to 1/r' },
        { id: 'phy102-q153-o3', text: 'Proportional to 1/r²' },
        { id: 'phy102-q153-o4', text: 'Independent of r' },
    ],
    correctOptionId: 'phy102-q153-o2',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q154',
    text: "Ampere's circuital law states that:",
    options: [
        { id: 'phy102-q154-o1', text: '∮B·dl = μ₀I' },
        { id: 'phy102-q154-o2', text: '∮E·dl = μ₀I' },
        { id: 'phy102-q154-o3', text: '∮B·dl = 0' },
        { id: 'phy102-q154-o4', text: '∮E·dl = 0' },
    ],
    correctOptionId: 'phy102-q154-o1',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q155',
    text: 'The magnetic field inside a long solenoid is:',
    options: [
        { id: 'phy102-q155-o1', text: 'Zero' },
        { id: 'phy102-q155-o2', text: 'Uniform' },
        { id: 'phy102-q155-o3', text: 'Non-uniform' },
        { id: 'phy102-q155-o4', text: 'Radial' },
    ],
    correctOptionId: 'phy102-q155-o2',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q156',
    text: 'The magnetic force on a current-carrying conductor in a magnetic field is given by:',
    options: [
        { id: 'phy102-q156-o1', text: 'F = I(L × B)' },
        { id: 'phy102-q156-o2', text: 'F = I(B × L)' },
        { id: 'phy102-q156-o3', text: 'F = B(I × L)' },
        { id: 'phy102-q156-o4', text: 'F = L(I × B)' },
    ],
    correctOptionId: 'phy102-q156-o1',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q157',
    text: 'The torque on a current loop in a magnetic field is maximum when the plane of the loop is:',
    options: [
        { id: 'phy102-q157-o1', text: 'Parallel to the field' },
        { id: 'phy102-q157-o2', text: 'Perpendicular to the field' },
        { id: 'phy102-q157-o3', text: 'At 45° to the field' },
        { id: 'phy102-q157-o4', text: 'Independent of orientation' },
    ],
    correctOptionId: 'phy102-q157-o1',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q158',
    text: 'A galvanometer can be converted into an ammeter by:',
    options: [
        { id: 'phy102-q158-o1', text: 'Connecting a high resistance in series' },
        { id: 'phy102-q158-o2', text: 'Connecting a high resistance in parallel' },
        { id: 'phy102-q158-o3', text: 'Connecting a low resistance in series' },
        { id: 'phy102-q158-o4', text: 'Connecting a low resistance in parallel' },
    ],
    correctOptionId: 'phy102-q158-o4',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q159',
    text: 'A galvanometer can be converted into a voltmeter by:',
    options: [
        { id: 'phy102-q159-o1', text: 'Connecting a high resistance in series' },
        { id: 'phy102-q159-o2', text: 'Connecting a high resistance in parallel' },
        { id: 'phy102-q159-o3', text: 'Connecting a low resistance in series' },
        { id: 'phy102-q159-o4', text: 'Connecting a low resistance in parallel' },
    ],
    correctOptionId: 'phy102-q159-o1',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q160',
    text: 'Moving coil galvanometer works on the principle of:',
    options: [
        { id: 'phy102-q160-o1', text: 'Heating effect of current' },
        { id: 'phy102-q160-o2', text: 'Magnetic effect of current' },
        { id: 'phy102-q160-o3', text: 'Chemical effect of current' },
        { id: 'phy102-q160-o4', text: 'Photoelectric effect' },
    ],
    correctOptionId: 'phy102-q160-o2',
    topic: 'Chapter 3: Magnetic Fields & Forces',
  },
  {
    id: 'phy102-q211',
    text: "Faraday's law states that the induced EMF is equal to:",
    options: [
        { id: 'phy102-q211-o1', text: 'Rate of change of magnetic flux' },
        { id: 'phy102-q211-o2', text: 'Magnetic flux' },
        { id: 'phy102-q211-o3', text: 'Current change' },
        { id: 'phy102-q211-o4', text: 'Resistance change' },
    ],
    correctOptionId: 'phy102-q211-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q212',
    text: "The negative sign in Faraday's law is explained by:",
    options: [
        { id: 'phy102-q212-o1', text: "Ohm's law" },
        { id: 'phy102-q212-o2', text: "Lenz's law" },
        { id: 'phy102-q212-o3', text: "Coulomb's law" },
        { id: 'phy102-q212-o4', text: "Ampere's law" },
    ],
    correctOptionId: 'phy102-q212-o2',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q213',
    text: "Lenz's law is a consequence of conservation of:",
    options: [
        { id: 'phy102-q213-o1', text: 'Charge' },
        { id: 'phy102-q213-o2', text: 'Energy' },
        { id: 'phy102-q213-o3', text: 'Momentum' },
        { id: 'phy102-q213-o4', text: 'Mass' },
    ],
    correctOptionId: 'phy102-q213-o2',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q214',
    text: 'The SI unit of magnetic flux is:',
    options: [
        { id: 'phy102-q214-o1', text: 'Tesla' },
        { id: 'phy102-q214-o2', text: 'Weber' },
        { id: 'phy102-q214-o3', text: 'Henry' },
        { id: 'phy102-q214-o4', text: 'Gauss' },
    ],
    correctOptionId: 'phy102-q214-o2',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q215',
    text: 'A coil with 100 turns has a magnetic flux of 0.5 Wb. If the flux reduces to zero in 0.2 seconds, the average induced EMF is:',
    options: [
        { id: 'phy102-q215-o1', text: '100 V' },
        { id: 'phy102-q215-o2', text: '250 V' },
        { id: 'phy102-q215-o3', text: '500 V' },
        { id: 'phy102-q215-o4', text: '1000 V' },
    ],
    correctOptionId: 'phy102-q215-o2',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q216',
    text: 'In a transformer, the ratio of secondary to primary voltage is equal to:',
    options: [
        { id: 'phy102-q216-o1', text: 'Ratio of turns' },
        { id: 'phy102-q216-o2', text: 'Ratio of currents' },
        { id: 'phy102-q216-o3', text: 'Ratio of powers' },
        { id: 'phy102-q216-o4', text: 'Ratio of resistances' },
    ],
    correctOptionId: 'phy102-q216-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q217',
    text: 'A step-up transformer:',
    options: [
        { id: 'phy102-q217-o1', text: 'Increases voltage' },
        { id: 'phy102-q217-o2', text: 'Decreases voltage' },
        { id: 'phy102-q217-o3', text: 'Increases current' },
        { id: 'phy102-q217-o4', text: 'Decreases power' },
    ],
    correctOptionId: 'phy102-q217-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q218',
    text: 'For an ideal transformer, the relationship between primary and secondary currents is:',
    options: [
        { id: 'phy102-q218-o1', text: 'Iₚ/Iₛ = Nₛ/Nₚ' },
        { id: 'phy102-q218-o2', text: 'Iₚ/Iₛ = Nₚ/Nₛ' },
        { id: 'phy102-q218-o3', text: 'Iₚ/Iₛ = (Nₚ/Nₛ)²' },
        { id: 'phy102-q218-o4', text: 'Iₚ/Iₛ = 1' },
    ],
    correctOptionId: 'phy102-q218-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q219',
    text: 'Eddy currents are:',
    options: [
        { id: 'phy102-q219-o1', text: 'Induced currents in conductors' },
        { id: 'phy102-q219-o2', text: 'Direct currents' },
        { id: 'phy102-q219-o3', text: 'Currents in resistors' },
        { id: 'phy102-q219-o4', text: 'Battery currents' },
    ],
    correctOptionId: 'phy102-q219-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q220',
    text: 'Self-inductance of a coil depends on:',
    options: [
        { id: 'phy102-q220-o1', text: 'Current through it' },
        { id: 'phy102-q220-o2', text: 'Voltage across it' },
        { id: 'phy102-q220-o3', text: 'Geometry of the coil' },
        { id: 'phy102-q220-o4', text: 'Resistance of the coil' },
    ],
    correctOptionId: 'phy102-q220-o3',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q221',
    text: 'The SI unit of self-inductance is:',
    options: [
        { id: 'phy102-q221-o1', text: 'Ohm' },
        { id: 'phy102-q221-o2', text: 'Farad' },
        { id: 'phy102-q221-o3', text: 'Henry' },
        { id: 'phy102-q221-o4', text: 'Weber' },
    ],
    correctOptionId: 'phy102-q221-o3',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q222',
    text: 'In an AC circuit with pure resistance:',
    options: [
        { id: 'phy102-q222-o1', text: 'Current leads voltage' },
        { id: 'phy102-q222-o2', text: 'Current lags voltage' },
        { id: 'phy102-q222-o3', text: 'Current and voltage are in phase' },
        { id: 'phy102-q222-o4', text: 'Current and voltage are 180° out of phase' },
    ],
    correctOptionId: 'phy102-q222-o3',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q223',
    text: 'In an AC circuit with pure capacitance:',
    options: [
        { id: 'phy102-q223-o1', text: 'Current leads voltage by 90°' },
        { id: 'phy102-q223-o2', text: 'Current lags voltage by 90°' },
        { id: 'phy102-q223-o3', text: 'Current and voltage are in phase' },
        { id: 'phy102-q223-o4', text: 'Current and voltage are 180° out of phase' },
    ],
    correctOptionId: 'phy102-q223-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q224',
    text: 'In an AC circuit with pure inductance:',
    options: [
        { id: 'phy102-q224-o1', text: 'Current leads voltage by 90°' },
        { id: 'phy102-q224-o2', text: 'Current lags voltage by 90°' },
        { id: 'phy102-q224-o3', text: 'Current and voltage are in phase' },
        { id: 'phy102-q224-o4', text: 'Current and voltage are 180° out of phase' },
    ],
    correctOptionId: 'phy102-q224-o2',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q225',
    text: 'The capacitive reactance is given by:',
    options: [
        { id: 'phy102-q225-o1', text: 'Xc = 1/(ωC)' },
        { id: 'phy102-q225-o2', text: 'Xc = ωC' },
        { id: 'phy102-q225-o3', text: 'Xc = 1/(ωL)' },
        { id: 'phy102-q225-o4', text: 'Xc = ωL' },
    ],
    correctOptionId: 'phy102-q225-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q226',
    text: 'The inductive reactance is given by:',
    options: [
        { id: 'phy102-q226-o1', text: 'Xʟ = 1/(ωC)' },
        { id: 'phy102-q226-o2', text: 'Xʟ = ωC' },
        { id: 'phy102-q226-o3', text: 'Xʟ = 1/(ωL)' },
        { id: 'phy102-q226-o4', text: 'Xʟ = ωL' },
    ],
    correctOptionId: 'phy102-q226-o4',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q227',
    text: 'In an RLC series circuit, resonance occurs when:',
    options: [
        { id: 'phy102-q227-o1', text: 'Xʟ = Xc' },
        { id: 'phy102-q227-o2', text: 'R = Xʟ' },
        { id: 'phy102-q227-o3', text: 'R = Xc' },
        { id: 'phy102-q227-o4', text: 'Xʟ = 0' },
    ],
    correctOptionId: 'phy102-q227-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q228',
    text: 'At resonance in an RLC circuit, the impedance is:',
    options: [
        { id: 'phy102-q228-o1', text: 'Maximum' },
        { id: 'phy102-q228-o2', text: 'Minimum' },
        { id: 'phy102-q228-o3', text: 'Zero' },
        { id: 'phy102-q228-o4', text: 'Infinite' },
    ],
    correctOptionId: 'phy102-q228-o2',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q229',
    text: 'The power factor in an AC circuit is given by:',
    options: [
        { id: 'phy102-q229-o1', text: 'cos φ = R/Z' },
        { id: 'phy102-q229-o2', text: 'cos φ = Xʟ/Z' },
        { id: 'phy102-q229-o3', text: 'cos φ = Xc/Z' },
        { id: 'phy102-q229-o4', text: 'cos φ = Z/R' },
    ],
    correctOptionId: 'phy102-q229-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q230',
    text: 'The RMS value of AC current is related to peak value by:',
    options: [
        { id: 'phy102-q230-o1', text: 'Iᵣₘₛ = I₀/√2' },
        { id: 'phy102-q230-o2', text: 'Iᵣₘₛ = I₀√2' },
        { id: 'phy102-q230-o3', text: 'Iᵣₘₛ = I₀/2' },
        { id: 'phy102-q230-o4', text: 'Iᵣₘₛ = I₀' },
    ],
    correctOptionId: 'phy102-q230-o1',
    topic: 'Chapter 4: Electromagnetic Induction',
  },
  {
    id: 'phy102-q261',
    text: 'Who discovered radioactivity?',
    options: [
        { id: 'phy102-q261-o1', text: 'Marie Curie' },
        { id: 'phy102-q261-o2', text: 'Pierre Curie' },
        { id: 'phy102-q261-o3', text: 'Becquerel' },
        { id: 'phy102-q261-o4', text: 'Rutherford' },
    ],
    correctOptionId: 'phy102-q261-o3',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q262',
    text: 'Which radiation has the highest penetrating power?',
    options: [
        { id: 'phy102-q262-o1', text: 'Alpha' },
        { id: 'phy102-q262-o2', text: 'Beta' },
        { id: 'phy102-q262-o3', text: 'Gamma' },
        { id: 'phy102-q262-o4', text: 'All have same' },
    ],
    correctOptionId: 'phy102-q262-o3',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q263',
    text: 'Which radiation has the highest ionizing power?',
    options: [
        { id: 'phy102-q263-o1', text: 'Alpha' },
        { id: 'phy102-q263-o2', text: 'Beta' },
        { id: 'phy102-q263-o3', text: 'Gamma' },
        { id: 'phy102-q263-o4', text: 'All have same' },
    ],
    correctOptionId: 'phy102-q263-o1',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q264',
    text: 'Alpha particles are:',
    options: [
        { id: 'phy102-q264-o1', text: 'Electrons' },
        { id: 'phy102-q264-o2', text: 'Protons' },
        { id: 'phy102-q264-o3', text: 'Helium nuclei' },
        { id: 'phy102-q264-o4', text: 'Photons' },
    ],
    correctOptionId: 'phy102-q264-o3',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q265',
    text: 'Gamma rays are:',
    options: [
        { id: 'phy102-q265-o1', text: 'Charged particles' },
        { id: 'phy102-q265-o2', text: 'Electromagnetic radiation' },
        { id: 'phy102-q265-o3', text: 'Sound waves' },
        { id: 'phy102-q265-o4', text: 'Neutrons' },
    ],
    correctOptionId: 'phy102-q265-o2',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q266',
    text: 'In β⁻ decay:',
    options: [
        { id: 'phy102-q266-o1', text: 'A neutron becomes a proton' },
        { id: 'phy102-q266-o2', text: 'A proton becomes a neutron' },
        { id: 'phy102-q266-o3', text: 'Nucleus loses helium nucleus' },
        { id: 'phy102-q266-o4', text: 'Nucleus captures electron' },
    ],
    correctOptionId: 'phy102-q266-o1',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q267',
    text: 'The half-life of a radioactive element is 10 days. What fraction remains after 30 days?',
    options: [
        { id: 'phy102-q267-o1', text: '1/2' },
        { id: 'phy102-q267-o2', text: '1/4' },
        { id: 'phy102-q267-o3', text: '1/8' },
        { id: 'phy102-q267-o4', text: '1/16' },
    ],
    correctOptionId: 'phy102-q267-o3',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q268',
    text: 'The decay constant λ and half-life T₁/₂ are related by:',
    options: [
        { id: 'phy102-q268-o1', text: 'λT₁/₂ = 0.693' },
        { id: 'phy102-q268-o2', text: 'λT₁/₂ = 1' },
        { id: 'phy102-q268-o3', text: 'λ/T₁/₂ = 0.693' },
        { id: 'phy102-q268-o4', text: 'T₁/₂/λ = 0.693' },
    ],
    correctOptionId: 'phy102-q268-o1',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q269',
    text: 'Nuclear fission involves:',
    options: [
        { id: 'phy102-q269-o1', text: 'Combining light nuclei' },
        { id: 'phy102-q269-o2', text: 'Splitting heavy nuclei' },
        { id: 'phy102-q269-o3', text: 'Radioactive decay' },
        { id: 'phy102-q269-o4', text: 'Electron emission' },
    ],
    correctOptionId: 'phy102-q269-o2',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q270',
    text: 'Nuclear fusion involves:',
    options: [
        { id: 'phy102-q270-o1', text: 'Combining light nuclei' },
        { id: 'phy102-q270-o2', text: 'Splitting heavy nuclei' },
        { id: 'phy102-q270-o3', text: 'Radioactive decay' },
        { id: 'phy102-q270-o4', text: 'Electron emission' },
    ],
    correctOptionId: 'phy102-q270-o1',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q271',
    text: 'A pure semiconductor is called:',
    options: [
        { id: 'phy102-q271-o1', text: 'Extrinsic semiconductor' },
        { id: 'phy102-q271-o2', text: 'Intrinsic semiconductor' },
        { id: 'phy102-q271-o3', text: 'N-type semiconductor' },
        { id: 'phy102-q271-o4', text: 'P-type semiconductor' },
    ],
    correctOptionId: 'phy102-q271-o2',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q272',
    text: 'In an N-type semiconductor, majority charge carriers are:',
    options: [
        { id: 'phy102-q272-o1', text: 'Holes' },
        { id: 'phy102-q272-o2', text: 'Electrons' },
        { id: 'phy102-q272-o3', text: 'Protons' },
        { id: 'phy102-q272-o4', text: 'Neutrons' },
    ],
    correctOptionId: 'phy102-q272-o2',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q273',
    text: 'In a P-type semiconductor, majority charge carriers are:',
    options: [
        { id: 'phy102-q273-o1', text: 'Holes' },
        { id: 'phy102-q273-o2', text: 'Electrons' },
        { id: 'phy102-q273-o3', text: 'Protons' },
        { id: 'phy102-q273-o4', text: 'Neutrons' },
    ],
    correctOptionId: 'phy102-q273-o1',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q274',
    text: 'A PN junction diode allows current to flow:',
    options: [
        { id: 'phy102-q274-o1', text: 'In both directions' },
        { id: 'phy102-q274-o2', text: 'Only in reverse bias' },
        { id: 'phy102-q274-o3', text: 'Only in forward bias' },
        { id: 'phy102-q274-o4', text: 'Never conducts' },
    ],
    correctOptionId: 'phy102-q274-o3',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q275',
    text: 'A Zener diode is used for:',
    options: [
        { id: 'phy102-q275-o1', text: 'Rectification' },
        { id: 'phy102-q275-o2', text: 'Voltage regulation' },
        { id: 'phy102-q275-o3', text: 'Amplification' },
        { id: 'phy102-q275-o4', text: 'Switching' },
    ],
    correctOptionId: 'phy102-q275-o2',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q276',
    text: 'A transistor has:',
    options: [
        { id: 'phy102-q276-o1', text: 'Two PN junctions' },
        { id: 'phy102-q276-o2', text: 'One PN junction' },
        { id: 'phy102-q276-o3', text: 'Three PN junctions' },
        { id: 'phy102-q276-o4', text: 'No PN junctions' },
    ],
    correctOptionId: 'phy102-q276-o1',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q277',
    text: 'The main functions of a transistor are:',
    options: [
        { id: 'phy102-q277-o1', text: 'Rectification and regulation' },
        { id: 'phy102-q277-o2', text: 'Amplification and switching' },
        { id: 'phy102-q277-o3', text: 'Detection and modulation' },
        { id: 'phy102-q277-o4', text: 'Filtering and smoothing' },
    ],
    correctOptionId: 'phy102-q277-o2',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q278',
    text: 'LED stands for:',
    options: [
        { id: 'phy102-q278-o1', text: 'Light Emitting Diode' },
        { id: 'phy102-q278-o2', text: 'Low Energy Device' },
        { id: 'phy102-q278-o3', text: 'Light Enhancing Diode' },
        { id: 'phy102-q278-o4', text: 'Low Emission Detector' },
    ],
    correctOptionId: 'phy102-q278-o1',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q279',
    text: 'A photodiode is used to:',
    options: [
        { id: 'phy102-q279-o1', text: 'Emit light' },
        { id: 'phy102-q279-o2', text: 'Detect light' },
        { id: 'phy102-q279-o3', text: 'Regulate voltage' },
        { id: 'phy102-q279-o4', text: 'Amplify signals' },
    ],
    correctOptionId: 'phy102-q279-o2',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q280',
    text: 'The number of nuclei of a radioactive substance reduces to 1/8 of original in 60 minutes. The half-life is:',
    options: [
        { id: 'phy102-q280-o1', text: '10 minutes' },
        { id: 'phy102-q280-o2', text: '15 minutes' },
        { id: 'phy102-q280-o3', text: '20 minutes' },
        { id: 'phy102-q280-o4', text: '30 minutes' },
    ],
    correctOptionId: 'phy102-q280-o3',
    topic: 'Chapter 5: Modern Physics',
  },
  {
    id: 'phy102-q301',
    text: 'A 10 μF capacitor is charged to 200 V. The energy stored is:',
    options: [
        { id: 'phy102-q301-o1', text: '0.1 J' },
        { id: 'phy102-q301-o2', text: '0.2 J' },
        { id: 'phy102-q301-o3', text: '0.4 J' },
        { id: 'phy102-q301-o4', text: '0.8 J' },
    ],
    correctOptionId: 'phy102-q301-o2',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q302',
    text: 'Three resistors 2Ω, 3Ω, and 5Ω are connected in parallel. The equivalent resistance is:',
    options: [
        { id: 'phy102-q302-o1', text: '1.03 Ω' },
        { id: 'phy102-q302-o2', text: '0.97 Ω' },
        { id: 'phy102-q302-o3', text: '10 Ω' },
        { id: 'phy102-q302-o4', text: '1.5 Ω' },
    ],
    correctOptionId: 'phy102-q302-o2',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q303',
    text: 'A proton moves with velocity 10⁶ m/s perpendicular to a magnetic field of 0.5 T. The force on the proton is:',
    options: [
        { id: 'phy102-q303-o1', text: '8 × 10⁻¹⁴ N' },
        { id: 'phy102-q303-o2', text: '4 × 10⁻¹⁴ N' },
        { id: 'phy102-q303-o3', text: '2 × 10⁻¹⁴ N' },
        { id: 'phy102-q303-o4', text: '1 × 10⁻¹⁴ N' },
    ],
    correctOptionId: 'phy102-q303-o1',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q304',
    text: 'In an AC circuit, V = 100 sin(314t) and I = 10 sin(314t - π/3). The power factor is:',
    options: [
        { id: 'phy102-q304-o1', text: '0.5' },
        { id: 'phy102-q304-o2', text: '0.866' },
        { id: 'phy102-q304-o3', text: '0.707' },
        { id: 'phy102-q304-o4', text: '1.0' },
    ],
    correctOptionId: 'phy102-q304-o1',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q305',
    text: 'A radioactive element has half-life of 5 days. The fraction that decays in 15 days is:',
    options: [
        { id: 'phy102-q305-o1', text: '1/8' },
        { id: 'phy102-q305-o2', text: '7/8' },
        { id: 'phy102-q305-o3', text: '3/4' },
        { id: 'phy102-q305-o4', text: '1/4' },
    ],
    correctOptionId: 'phy102-q305-o2',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q306',
    text: 'A transformer has 100 primary turns and 1000 secondary turns. If input voltage is 220 V AC, output voltage is:',
    options: [
        { id: 'phy102-q306-o1', text: '22 V' },
        { id: 'phy102-q306-o2', text: '220 V' },
        { id: 'phy102-q306-o3', text: '2200 V' },
        { id: 'phy102-q306-o4', text: '440 V' },
    ],
    correctOptionId: 'phy102-q306-o3',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q307',
    text: 'In an RLC series circuit, R = 10Ω, Xʟ = 20Ω, Xc = 10Ω. The impedance is:',
    options: [
        { id: 'phy102-q307-o1', text: '10√2 Ω' },
        { id: 'phy102-q307-o2', text: '20 Ω' },
        { id: 'phy102-q307-o3', text: '10 Ω' },
        { id: 'phy102-q307-o4', text: '40 Ω' },
    ],
    correctOptionId: 'phy102-q307-o1',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q308',
    text: 'A wire of resistance 4Ω is stretched to double its length. The new resistance is:',
    options: [
        { id: 'phy102-q308-o1', text: '4Ω' },
        { id: 'phy102-q308-o2', text: '8Ω' },
        { id: 'phy102-q308-o3', text: '16Ω' },
        { id: 'phy102-q308-o4', text: '2Ω' },
    ],
    correctOptionId: 'phy102-q308-o3',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q309',
    text: 'The magnetic field at the center of a circular coil of radius 10 cm carrying 2 A current is:',
    options: [
        { id: 'phy102-q309-o1', text: '1.26 × 10⁻⁵ T' },
        { id: 'phy102-q309-o2', text: '2.52 × 10⁻⁵ T' },
        { id: 'phy102-q309-o3', text: '3.14 × 10⁻⁵ T' },
        { id: 'phy102-q309-o4', text: '4.52 × 10⁻⁵ T' },
    ],
    correctOptionId: 'phy102-q309-o1',
    topic: 'Final Questions (Calculation & Application Focus)',
  },
  {
    id: 'phy102-q310',
    text: "A 500-turn coil has cross-sectional area 0.04 m². It's placed in a magnetic field of 0.2 T. If the field reduces to zero in 0.1 s, the induced EMF is:",
    options: [
        { id: 'phy102-q310-o1', text: '4 V' },
        { id: 'phy102-q310-o2', text: '40 V' },
        { id: 'phy102-q310-o3', text: '400 V' },
        { id: 'phy102-q310-o4', text: '4000 V' },
    ],
    correctOptionId: 'phy102-q310-o2',
    topic: 'Final Questions (Calculation & Application Focus)',
  }
];
